### ISSUE TITLE
Is there any way to declare own protected dependecies list?

### ISSUE THREAD

**Issue by Insolita** [kalessil/production-dependencies-guard#1]
Currently, it check and prevent to install dependencies declared in Repository, so if someone  create library for dev  purpose,than he, or community should  add PR with new package in this repo. But what about internal project packages for dev, that often has created for big complex projects

**Comment by Insolita** [comment]
Also, there may be some exceptional cases. For example  i 'm familiar with project that use fzaninotto/faker in production, because the generation random data by rules - it is part of business logic

**Comment by kalessil** [comment]
We could use type property of composer-manifest, e.g. code sniffer coding standards has it set to `"type": "phpcodesniffer-standard"`. If there are commonly agreed type for development-only packages, then it should be quite straightforward to implement.

**Comment by kalessil** [comment]
Hi @fzaninotto, is `fzaninotto/faker` intended for use in production environments?

**Comment by kalessil** [comment]
Since faker documentation says `composer require fzaninotto/faker`, let's assume it can be used in production, I'll drop it from the list.

**Comment by kalessil** [comment]
@Insolita: #6 should cover the custom dev-packages detection topic.
