### ISSUE TITLE
Show "composer why" among dev-package

### ISSUE THREAD

**Issue by ScreamingDev** [kalessil/production-dependencies-guard#12]
This error is shown:

```
 [RuntimeException]                                                                    
  Dependencies guard has found violations in require-dependencies (source: lock-file):  
   - symfony/debug: dev-package-name  
```

But I did not require this package so I need to ask `composer why` .
It would be great if the error message already shows that symfony/console brought this upon us.

Aside: A bit sad that everything gets block due to symfony/console .

**Comment by kalessil** [comment]
Filed the console-component issue here: https://github.com/symfony/symfony/issues/31379 (in my project I white-listed the component + one more from symfony for now).

Will check if I can extract information from lock-file about which package bringing the dependency.

**Comment by kalessil** [comment]
Done!
