### ISSUE TITLE
Composer 2 support

### ISSUE THREAD

**Issue by voku** [kalessil/production-dependencies-guard#15]
I see this error message:

```
kalessil/production-dependencies-guard dev-master requires composer-plugin-api ^1.1 -> found composer-plugin-api[2.0.0] but it does not match the constraint.

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.
```

**Comment by jammyproject** [comment]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires zendframework/zend-skeleton-installer ^0.1.7 || ^1.0 -> satisfiable by zendframework/zend-skeleton-installer[0.1.7].
    - zendframework/zend-skeleton-installer 0.1.7 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 2
    - zendframework/zend-component-installer[1.0.0, ..., 1.1.1, 2.1.0, ..., 2.1.2] require composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - Root composer.json requires zendframework/zend-component-installer ^1.0 || ^2.1 -> satisfiable by zendframework/zend-component-installer[1.0.0, 1.1.0, 1.1.1, 2.1.0, 2.1.1, 2.1.2].

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.

**Comment by jammyproject** [comment]
I have same issue:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires zendframework/zend-skeleton-installer ^0.1.7 || ^1.0 -> satisfiable by zendframework/zend-skeleton-installer[0.1.7].
    - zendframework/zend-skeleton-installer 0.1.7 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 2
    - zendframework/zend-component-installer[1.0.0, ..., 1.1.1, 2.1.0, ..., 2.1.2] require composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - Root composer.json requires zendframework/zend-component-installer ^1.0 || ^2.1 -> satisfiable by zendframework/zend-component-installer[1.0.0, 1.1.0, 1.1.1, 2.1.0, 2.1.1, 2.1.2].

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.

**Comment by kalessil** [comment]
Foxed!

**Comment by promko** [comment]
I'm afraid not foxed nor fixed yet :-(
I tried to
**php composer.phar create-project -sdev zendframework/skeleton-application helloworld**
**_... and got errors (please see below):_**
Creating a "zendframework/skeleton-application" project at "./helloworld"
Installing zendframework/skeleton-application (3.1.3)
  - Installing zendframework/skeleton-application (3.1.3): Extracting archive
Created project in /home/roman/helloworld
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires zendframework/zend-skeleton-installer ^0.1.7 || ^1.0 -> satisfiable by zendframework/zend-skeleton-installer[0.1.7].
    - zendframework/zend-skeleton-installer 0.1.7 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.1.0] but it does not match the constraint.
  Problem 2
    - zendframework/zend-component-installer[1.0.0, ..., 1.1.1, 2.1.0, ..., 2.1.2] require composer-plugin-api ^1.0 -> found composer-plugin-api[2.1.0] but it does not match the constraint.
    - Root composer.json requires zendframework/zend-component-installer ^1.0 || ^2.1 -> satisfiable by zendframework/zend-component-installer[1.0.0, 1.1.0, 1.1.1, 2.1.0, 2.1.1, 2.1.2].

**Comment by budakbajupurple** [comment]
how to update your plugins? is this problem solve?
