### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by SunMar** [kalessil/production-dependencies-guard#16]
Hi,

The current `composer.json` PHP requirement for `^7.0` blocks upgrading to PHP 8. Is it possible to expand to `^7.0|^8.0` or are there any known incompatibilities?

Thanks!

**Comment by kalessil** [comment]
Hi. Yes, it should be possible. I'll push the changes later today.

**Comment by kalessil** [comment]
Thank you for your patience @SunMar, PHP 8 support is enabled.
