### ISSUE TITLE
Feedback: new dependencies

### ISSUE THREAD

**Issue by kalessil** [kalessil/production-dependencies-guard#3]
- nunomaduro/collision
- beyondcode/laravel-dump-server

**Comment by Insolita** [comment]
wnx/laravel-stats
insolita/yii2-codestat
phploc/phploc

**Comment by tommy-muehle** [comment]
Hi @kalessil,

nice idea! Maybe also a further way would be to filter by composer "keywords". (https://getcomposer.org/doc/04-schema.md#keywords) 

For example a tool or library with the keyword "analyzer" should not part of the require-section.

**Comment by kalessil** [comment]
@Insolita: thanks!
@tommy-muehle: oh, might be a good source too, thanks!

**Comment by kalessil** [comment]
@tommy-muehle: filed a new issue - #6

**Comment by kalessil** [comment]
Added!
