### ISSUE TITLE
FR: `accept-license:xxx` if `check-license` presented

### ISSUE THREAD

**Issue by kalessil** [kalessil/production-dependencies-guard#8]

**Comment by shochdoerfer** [comment]
Maybe a whitelist makes more sense. Otherwise I have to constantly monitor the used licenses and include the ones in the `disallow-license` list. Default would be allow anything, once the setting is enabled only licenses that are part of the defined list are allowed.

**Comment by kalessil** [comment]
@shochdoerfer : sounds great

**Comment by kalessil** [comment]
Implemented!

**Comment by ScreamingDev** [comment]
That was faster than I could have a look and I like it! :D
But also a bit sad about composer that things are not nested like

```
"white-list:not this but..."
"white-list": [
  "this",
  "yay",
]
```

**Comment by kalessil** [comment]
Yep, json is not allowing to do
```
{
    "string-setting", /* needs key, and `"setting": "setting"` is silly */
    "array-setting": [ ... ]
}
```
